name: Solar-system application workflow

on:
  workflow_dispatch:
  push:
    branches: ["main", "feature/*"]

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
#  NODE_ENV:

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Download source code
        uses: actions/checkout@v4

      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: List reports
        run: ls -lart

      - name: Archive and upload reports
        uses: actions/upload-artifact@v3
        with:
          name: Mocha-Test-Report
          path: test-results.xml
