name: Solar-system application workflow

on:
  workflow_dispatch:
  push:
    branches: ["main", "feature/*"]

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
#  NODE_ENV:

jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        node_version: [18, 19, 20]
        os: ['ubuntu-latest', 'macos-latest']
        exclude:
          - node_version: 18
            os: 'macos-latest'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download source code
        uses: actions/checkout@v4

      - name: Install nodejs (version ${{ matrix.node_version }})
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: List reports
        run: ls -lart

      - name: Archive and upload reports
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-Test-Report-${{ matrix.os }}-${{ matrix.node_version }}
          path: test-results.xml
